# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EquipmentManagement' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EquipmentManagement
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'
  pod 'KeychainSwift', '~> 20.0'
end
