# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Scan QR Code' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Scan QR Code
  pod 'QR-Code-Scanner-iOS', '~> 1.0'

end
